Adding nodejs web app to demonstrate generation of client sdk using API Center extension
Azure-Samples/APICenter-Reference pull request #43
Opened 2024-07-16 08:45 UTC by juliamuiruri4

## Purpose

* Adding nodejs/webapp project for client sdk geenration.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code
```
Fork 👉 https://github.com/juliamuiruri4/APICenter-Reference _(get all branches)_
git clone https://github.com/<username>/APICenter-Reference
cd APICenter-Reference
git checkout api-prod
```

* Register API
Register the WeatherAPI in your API Center. Here is the openapi spec file 👉 [weather-forecast.json](https://github.com/user-attachments/files/16245611/weather-forecast.json)

* Test the code

Follow steps at https://github.com/juliamuiruri4/APICenter-Reference/blob/api-prod/docs/api-client-sdk-integration-javascript.md#api-client-sdk-integration

## What to Check
Verify that the following are valid
* WebApp successfully runs and pulls data from the web api
![image](https://github.com/user-attachments/assets/ea40f72d-3e3d-4dda-8900-b3f5efac1470)

## Other Information

Note, API Center extension client generation capability is not yet supported in codespaces.

2024-07-16 08:48 UTC, juliamuiruri4 commented
@justinyoo

2024-07-18 14:34 UTC, justinyoo requested changes
Thanks @juliamuiruri4! I left a few comments for you to take a look.

2024-07-18 14:34 UTC, justinyoo commented on docs/api-client-sdk-integration-javascript.md
Can we rename this file to `-nodejs.md` like the other files?

2024-07-18 14:34 UTC, justinyoo commented on docs/images/api-client-sdk-integration-javascript-01.png
Rename the filename to `-nodejs-**.png` and all the image files.

2024-07-18 14:34 UTC, justinyoo commented on nodejs/webapp/src/ApiClients/models/index.ts
We should NOT include all the files under the `ApiClients` directory.

2024-07-18 19:09 UTC, juliamuiruri4 commented on docs/api-client-sdk-integration-javascript.md
Done

2024-07-18 19:19 UTC, juliamuiruri4 commented on docs/images/api-client-sdk-integration-javascript-01.png
Done

2024-07-18 19:23 UTC, juliamuiruri4 commented on nodejs/webapp/src/ApiClients/models/index.ts
Done

2024-07-19 04:58 UTC, justinyoo requested changes
@juliamuiruri4 Mostly looks OK except this:

![image](https://github.com/user-attachments/assets/88b704c6-62c5-444e-a783-1baee7de7028)

Would you please update your npm packages?

2024-07-19 13:43 UTC, justinyoo requested changes
I left more comments, based on the discussion on the other channel.

2024-07-19 13:43 UTC, justinyoo commented on docs/images/api-client-sdk-integration-nodejs-03.png
Can we change the screenshot "WITHOUT" the `1K+` badge? I think it's because you've taken this screenshot after deploying analyser and portal.

2024-07-19 13:43 UTC, justinyoo commented on docs/images/api-client-sdk-integration-nodejs-04.png
Can we change the screenshot "WITHOUT" the `1K+` badge? I think it's because you've taken this screenshot after deploying analyser and portal.

2024-07-19 13:43 UTC, justinyoo commented on README.md
There's another README doc under the `/docs` directory. Please update that file as well.

2024-07-19 13:43 UTC, justinyoo commented on nodejs/webapp/package.json
Please update the npm packages to get rid of all security vulnerabilities.

2024-07-19 14:33 UTC, justinyoo requested changes

2024-07-19 14:33 UTC, justinyoo commented on docs/images/api-client-sdk-integration-nodejs-01.png
Can we change the screenshot "WITHOUT" the 1K+ badge? I think it's because you've taken this screenshot after deploying analyser and portal.

2024-07-22 14:21 UTC, merged